version: '3.8'

services:
  frontend:
    image: omer5yerushalmi/frontend:0.3
    ports:
      - "443:443"
    volumes:
      - ./ssl:/ssl
    environment:
      - PORT=443
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: omer5yerushalmi/backend:0.3
    ports:
      - "4000:4000"
    volumes:
      - ./ssl:/ssl
      - ./backend/public:/backend/public
      - ./backend/.env:/backend/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
